# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa8b6c927ed5c02be137f7826eecc5f3e55ba244c48eb26fd0fcab2edf121b1a7e9bc65229bb3dc2e68c92da693d2ce6f852a11c4e27c038d5fb6399747b708

test:
  secret_key_base: bc3c1bc1eb9b7e703d86459bffa66f34012a46e0b6e157095ce2bd3ddc5029d95db229d2825a4ecbf82d3d3c61170af3ebb45f4ce7a920a7cab27521b01d153a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
